adding BlockOwnerDeletion at MUR
codeready-toolchain/toolchain-common pull request #176
Opened 2021-05-18 18:40 UTC by ranakan19

setting BlockOwnerDeletion to true in OwnerReference for MUR, for foreground Garbage Collection

2021-05-18 18:55 UTC, alexeykazakov approved these changes

2021-05-19 09:29 UTC, MatousJobanek reviewed
May I ask what the purpose of this change is? This code is used only for test purposes.
In the production code, we call `SetControllerReference` which should set that field to true:
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controllerutil/controllerutil.go#L74-L81

2021-05-19 22:29 UTC, ranakan19 commented
Don't know if we still need this, since block owner deletion is set true [here](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controllerutil/controllerutil.go#L79) which is called from [here](https://github.com/codeready-toolchain/host-operator/blob/master/pkg/controller/usersignup/usersignup_controller.go#L511)
On second thought, it wouldn't harm and only ensures foreground deletion; WDYT?

2021-05-20 03:38 UTC, ranakan19 commented
> May I ask what the purpose of this change is? This code is used only for test purposes.
> In the production code, we call `SetControllerReference` which should set that field to true:
> https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controllerutil/controllerutil.go#L74-L81

sorry @MatousJobanek i saw your comment later, you are right, i probably don't need it.

2021-05-27 12:51 UTC, xcoulon requested changes

2021-05-27 12:51 UTC, xcoulon commented on pkg/test/masteruserrecord/master_user_record.go
> +					BlockOwnerDeletion: func(b bool) *bool { return &b }(true),
is it something you could test, to ensure it cannot be removed by accident in the future?

2021-06-04 16:18 UTC, alexeykazakov commented
@ranakan19 any updates on this PR?

2021-06-09 16:52 UTC, ranakan19 commented
closing as this change is not needed.

2021-06-09 16:52 UTC, closed without merging